export 'package:bacura_app/core/utils/color_manager.dart';
export 'package:flutter/material.dart';
export 'package:bacura_app/core/utils/routes_manager.dart';
export 'package:flutter_gen/gen_l10n/app_localizations.dart';
export 'package:bacura_app/feature/auth/presentation/controller/login_provider.dart';
export 'package:bacura_app/feature/auth/presentation/views/widgets/bacura_logo_container.dart';
export 'package:bacura_app/feature/auth/presentation/views/widgets/custom_phonefield.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:provider/provider.dart';
