import 'package:bacura_app/core/utils/app_strings.dart';

Map<String, String> coreAr = {
  AppStrings.noRouteFounded: 'لم يتم العثور على مسار',
  AppStrings.ar: 'ar',
  AppStrings.en: 'en',
  AppStrings.ar_en: 'AR',
  AppStrings.arabic: 'English',
  AppStrings.continueAsVisitor: 'الإستمرار كزائر',
  AppStrings.login: 'تسجيل الدخول',
  AppStrings.logout: 'تسجيل الخروج',
  AppStrings.edit: 'تعديل',
  AppStrings.register: 'تسجيل',
  AppStrings.dontHaveAccount: 'ليس لديك حساب ؟',
  AppStrings.createAccount: 'إنشاء حساب',
  AppStrings.fullName: 'الاسم',
  AppStrings.email: 'البريد الالكتروني',
  AppStrings.enterEmail: 'ادخل بريدك الالكتروني',
  AppStrings.pleaseEnterEmail: 'الرجاء إدخال البريد الإلكتروني',
  AppStrings.pleaseEnterValidEmail: 'الرجاء إدخال بريد إلكتروني صالح',
  AppStrings.gender: 'الجنس',
  AppStrings.city: 'المدينة',
  AppStrings.mobileNumber: 'رقم الهاتف',
  AppStrings.enterYourName: 'أدخل اسمك',
  AppStrings.pleaseEnterYourName: 'من فضلك أدخل اسمك',
  AppStrings.enterYourMobileNumber: 'أدخل رقم هاتفك',
  AppStrings.pleaseEnterYourMobileNumber: 'من فضلك أدخل رقم هاتفك',
  AppStrings.pleaseEnterValidMobileNumber: 'الرجاء إدخال رقم هاتف صالح',
  AppStrings.pleaseEnterNameAndMobileNumber: 'الرجاء إدخال الاسم ورقم الهاتف',
  AppStrings.inValidMobileNumber: 'رقم الهاتف غير صحيح',
  AppStrings.home: 'الرئيسية',
  AppStrings.offers: 'العروض',
  AppStrings.orders: 'طلباتي',
  AppStrings.more: 'المزيد',
  AppStrings.otp: 'رمز التحقق',
  AppStrings.pleaseEnterOtp: 'الرجاء إدخال رمز التحقق',
  AppStrings.otpShouldBeFourDigits: 'يجب أن يكون رمز التجقق 4 أرقام',
  AppStrings.otpVerified: 'تم التحقق من رمز التحقق',
  AppStrings.OtpSentTo: 'تم إرسال رمز التحقق الي',
  AppStrings.changeMobileNumber: 'تغيير الرقم؟',
  AppStrings.verify: 'تحقق',
  AppStrings.resend: 'إعادة الارسال',
  AppStrings.servicesReadyForYou: 'خدماتنا جاهزة لك!',
  AppStrings.specialServices: 'خدمات مميزة صنعت لأجلك',
  AppStrings.language: 'اللغة',
  AppStrings.aboutBacuraApp: 'عن تطبيق باكورة التقنيات',
  AppStrings.technicalSupport: 'الدعم الفني',
  AppStrings.termsAndConditions: 'الأحكام والشروط',
  AppStrings.privacyPolicy: 'سياسة الخصوصية',
  AppStrings.registerAsServiceProvider: 'التسجيل كمقدم خدمة',
  AppStrings.suggestions: 'الأقتراحات',
  AppStrings.pleaseEnterSuggestions: 'الرجاء إدخال اقتراحاتك',
  AppStrings.pleaseEnterAllData: 'الرجاء إدخال كافة البيانات',
  AppStrings.rateApp: 'قيّم التطبيق',
  AppStrings.shareApp: 'شارك التطبيق',
  AppStrings.bacuraStore: 'متجر باكورة',
  AppStrings.customerService: 'خدمة العملاء',
  AppStrings.ok: 'حسنا',
  AppStrings.acceptTerms: 'قبول سياسة الخصوصية والشروط والأحكام',
  AppStrings.continuePayment: 'الاستمرار للدفع',
  AppStrings.pay: 'دفع',
  AppStrings.serviceDetails: 'تفاصيل الخدمة',
  AppStrings.serviceType: 'نوع الخدمة',
  AppStrings.availableServices: 'الخدمات المتاحة',
  AppStrings.next: 'التالي',
  AppStrings.setDate: 'حدد اليوم المناسب للتواصل',
  AppStrings.setTime: 'حدد الوقت المناسب للتواصل',
  AppStrings.setLocation: 'اضغط على الأيقونة لتعيين الموقع',
  AppStrings.pleaseSelectLocation: 'الرجاء تحديد الموقع',
  AppStrings.setCurrentLocation: 'تعيين الموقع الحالي',
  AppStrings.neededServiceDescription: 'وصف الخدمة التي تحتاجها',
  AppStrings.serviceDescription: 'وصف الخدمة: ',
  AppStrings.enterServiceDescription: 'ادخل وصف الخدمة....',
  AppStrings.sendRequest: 'إرسال الطلب',
  AppStrings.yourSuggestions: 'اقتراحاتك',
  AppStrings.yourSuggestionsHint: 'اقتراحاتك مهمة......',
  AppStrings.send: 'إرسال',
  AppStrings.notifications: 'الإشعارات',
  AppStrings.offerDetails: 'تفاصيل العرض',
  AppStrings.read_more: 'قراءة المزيد',
  AppStrings.read_less: 'قراءة أقل',
  AppStrings.cancelOrder: 'إلغاء الطلب',
  AppStrings.closeOrder: 'إغلاق الطلب',
  AppStrings.orderDetails: 'تفاصيل الطلب',
  AppStrings.total: 'الإجمالي: ',
  AppStrings.location: 'الموقع: ',
  AppStrings.paymentMethod: 'طريقة الدفع: ',
  AppStrings.paymentStatus: 'حالة الدفع: ',
  AppStrings.warrantyStatus: 'حالة الضمان: ',
  AppStrings.manageOrder: 'إدارة الطلب',
  AppStrings.orderCancelled: 'تم إلغاء الطلب',
  AppStrings.printInvoice: 'طباعة الفاتورة',
  AppStrings.customerSupportChat: 'محادثة خدمة العملاء',
  AppStrings.consultationScreen: 'شاشة الاستشارة',
  AppStrings.consultationDescription: 'وصف الاستشارة',
  AppStrings.describeYourConsultation: 'اوصف استشارتك...',
  AppStrings.pleaseDescribeYourConsultation: 'الرجاء وصف استشارتك',
  AppStrings.consultationType: 'نوع الاستشارة',
  AppStrings.cancel: 'إلغاء',
  AppStrings.FAQ: 'الأسئلة الشائعة',
  AppStrings.complaints: 'الشكاوي',
  AppStrings.userGuide: 'دليل المستخدم',
  AppStrings.serviceProvider: 'مقدم الخدمة',
  AppStrings.technician: ' الفني',
  AppStrings.complaintType: 'نوع الشكوي',
  AppStrings.complaint: 'شكواك',
  AppStrings.enterYourComplaint: 'ادخل شكواك......',
  AppStrings.pleaseEnterYourComplaint: 'الرجاء إدخال شكواك',
  AppStrings.sendComplaint: 'إرسال الشكوي',
  AppStrings.invoice: 'الفاتورة',
  AppStrings.downloadInvoice: 'تحميل الفاتورة',
  AppStrings.save: 'حفظ',
  AppStrings.termsIntro:
      'مرحبًا بك في تطبيق باكورة التقنيات.\nتوفر هذه الشروط والأحكام الأساس القانوني لاستخدامك للتطبيق والخدمات المرتبطة به.\n\nقبول الشروط: باستخدام التطبيق، فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق على أي من هذه الشروط، يرجى عدم استخدام التطبيق',
  AppStrings.termsDefinitions: '1. التعاريف: ',
  AppStrings.termsDefinitionsContent:
      '- التطبيق: يشير إلى تطبيق Bacura وجميع خدماته والمحتوى المرتبط به.\n- الخدمات: تعني جميع الخدمات والميزات التي يوفرها التطبيق.\n- المستخدم: أي شخص يستخدم التطبيق أو أي من خدماته.\n- مزود الخدمة: أي طرف يقدم الخدمات الفعلية للمستخدمين النهائيين أو العملاء\n- مزود الخدمة: أي طرف يوفر البنية التحتية أو التقنيات أو الأنظمة التي يعتمد عليها التطبيق',
  AppStrings.termsConditions: '2. شروط الاستخدام: ',
  AppStrings.termsConditionsContent:
      '- الأهلية: يجب أن يكون المستخدمون في سن قانونية لإبرام عقد ملزم أو الحصول على موافقة والديهم أو الوصي القانوني لاستخدام التطبيق.\n                    \n- الاستخدام المقبول: يجب على المستخدمين استخدام التطبيق فقط للأغراض التي تم تصميم التطبيق من أجلها وبطريقة لا تنتهك حقوق الآخرين أو تؤثر سلبًا على تشغيل التطبيق. ويشمل ذلك عدم استخدام التطبيق للاحتيال أو المضايقة أو أي استخدام غير قانوني.\n\n- إنشاء الحساب: يجب عليك إنشاء حساب لتتمكن من استخدام خدمات التطبيق.\n\n- إرفاق المستندات: قد يتطلب استخدام بعض خدمات التطبيق إرفاق المستندات. يجب على المستخدمين تقديم معلومات صحيحة ودقيقة وحديثة عند إرسال هذه المستندات، والتأكد من أن جميع البيانات والمعلومات المقدمة تتوافق مع المتطلبات المحددة للخدمة.\n\n- الاستخدام المستمر: بمجرد نشر التعديلات على الشروط، فإن استخدامك للتطبيق بعد هذا التحديث يعتبر قبولاً للشروط المعدلة.\n\n- إنهاء الاستخدام: نحتفظ بالحق في إنهاء أو تعليق وصولك إلى التطبيق في أي وقت، دون إشعار مسبق، إذا انتهكت هذه الشروط.',
  AppStrings.termsCopyRights: ' 3. حقوق الملكية الفكرية:',
  AppStrings.termsCopyRightsContent:
      'جميع حقوق الطبع والنشر والعلامات التجارية وغيرها من الحقوق المتعلقة بالتطبيق ومحتوياته مملوكة لنا. لا يجوز نسخ أي جزء من التطبيق أو توزيعه أو تعديله دون إذن صريح منا.',
  AppStrings.termsLimitationOfLiability: '4. حدود المسؤولية:',
  AppStrings.termsLimitationOfLiabilityContent:
      'تخلي الشركة مسؤوليتها ولا تضمن أن يكون التطبيق خاليًا من الأخطاء أو العيوب أو أن الخدمات ستكون متاحة في جميع الأوقات.',
  AppStrings.termsChanges: '5. التغييرات:',
  AppStrings.termsChangesContent:
      '- تعديل الشروط: للشركة الحق في تعديل هذه الشروط في أي وقت.\n              \n- إلغاء الخدمة: للشركة الحق في إلغاء الخدمة أو أي جزء منها في أي وقت.',
  AppStrings.contactUs: '6. اتصل بنا:',
  AppStrings.contactUsContent:
      'إذا كانت لديك أي أسئلة حول هذه السياسة، يرجى الاتصال بنا على (info@bacura.com) أو (0547000015).',
  AppStrings.privacyPolicyIntro:
      ' مرحبًا بك في تطبيق باكورة التقنيات.\n\nنحن في تطبيق باكورة التقنيات ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الشخصية، تشرح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا وحماية المعلومات التي تقدمها لنا عند استخدامك للتطبيق\n',
  AppStrings.privacyCollectionOfInformation: '1. جمع المعلومات:',
  AppStrings.privacyCollectionOfInformationContent:
      'نحن نجمع المعلومات الشخصية التي تقدمها طواعية في التطبيق، مثل الاسم وعنوان البريد الإلكتروني ورقم الهاتف والمعلومات الأخرى التي قد نحتاجها لتقديم الخدمة وإرسال إشعارات أو تحديثات أو معلومات متعلقة بالخدمة أو حول العروض الخاصة والميزات الجديدة. نحن نجمع معلومات فنية حول كيفية استخدامك للتطبيق، وسجل لنشاطك في التطبيق، بما في ذلك الصفحات التي تزورها والميزات التي تستخدمها والوقت الذي تقضيه في استخدام التطبيق لغرض تحسين تجربة المستخدم وجودة الخدمة وتحليل استخدام التطبيق، ونحتفظ بمعلوماتك فقط طالما كان ذلك ضروريًا لتحقيق الأغراض التي تم جمعها من أجلها، أو حسبما يقتضيه القانون.\n',
  AppStrings.privacyInformationProtection: '2. حماية المعلومات',
  AppStrings.privacyInformationProtectionContent:
      'نحن ملتزمون بحماية معلوماتك الشخصية. ونتخذ التدابير الأمنية المناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو الاستخدام أو الكشف عنها أو تغييرها أو تدميرها. ويشمل ذلك استخدام تقنيات التشفير والأمن السيبراني للحفاظ على نظام أمان محدث.\n',
  AppStrings.privacySharingInformation: '3. مشاركة المعلومات:',
  AppStrings.privacySharingInformationContent:
      'قد نشارك معلوماتك الشخصية مع طرف ثالث ولكن فقط بالقدر الضروري لتحقيق الأغراض المحددة في هذه السياسة، مثل:\n- مقدمو الخدمات والمزودون: الشركات التي نتعاقد معها لتقديم خدمات معينة نيابة عنا.\n- الشركاء: الشركات التي نتعاون معها لتقديم عروض مشتركة.\n- الهيئات الحكومية: إذا كان القانون يفرض ذلك.',
  AppStrings.changesToThePrivacyPolicy: '4. التغييرات على سياسة الخصوصية:',
  AppStrings.changesToThePrivacyPolicyContent:
      'نحتفظ بالحق في تعديل هذه السياسة في أي وقت. وسنقوم بإخطارك بأي تغييرات جوهرية من خلال التطبيق أو عبر البريد الإلكتروني.\n',
  AppStrings.privacyUserRights: '5. حقوق المستخدم:',
  AppStrings.privacyUserRightsContent:
      'يمكنك الوصول إلى معلوماتك الشخصية وتصحيحها من خلال إعدادات الحساب في التطبيق أو عن طريق الاتصال بنا مباشرة. يمكنك إلغاء الاشتراك في الرسائل التسويقية أو حذف حسابك في أي وقت من خلال إعدادات الحساب أو عن طريق الاتصال بخدمة العملاء.',
  AppStrings.aboutUs:
      'مع تطبيق باكورة التقنيات، نوفر لك حلاً متكاملاً لإدارة احتياجاتك التقنية والذكية والأمنية بكل سهولة واحترافية. سواء كنت تبحث عن تركيب كاميرات مراقبة عالية الجودة أو أنظمة ذكية أو حلول تقنية مبتكرة لمنزلك أو مكان عملك، فإن تطبيقنا هو الخيار الأمثل.',
  AppStrings.aboutUsContent:
      'نضمن لك خدمات تقنية عالية الجودة بكفاءة وسرعة في التنفيذ، مع فريق عمل محترف على مدار الساعة ودعم فني متواصل، أمنك وراحتك الآن في متناول يدك.',
  AppStrings.ourLocation: 'موقعنا:  ',
  AppStrings.uploadImage: 'تم تحميل الصورة',
  AppStrings.takePicture: 'التقط صورة',
  AppStrings.selectFromGallery: 'اختر من المعرض',
  AppStrings.offerRequest: 'طلب العرض',
  AppStrings.browseAppWithoutRegister: 'يمكنك تصفح التطبيق بدون تسجيل',
  AppStrings.appLanguage: 'لغة التطبيق',
  AppStrings.male: 'ذكر',
  AppStrings.female: 'أنثي',
  AppStrings.typeMessageHere: 'اكتب رسالتك هنا',
  AppStrings.welcomeToBacuraApp: 'أهلا بك في تطبيق باكورة',
  AppStrings.confirm: 'تأكيد',
  AppStrings.yourComplaintSentSuccessfully: 'تم إرسال شكواك بنجاح',
  AppStrings.yourSuggestionSentSuccessfully: 'تم ارسال اقتراحك بنجاحك',
  AppStrings.yourSuggestionSentSuccessfullyMsg: 'يهمنا إهتمامك ونشكرك علي اقتراحك سيتم مراجعة اقتراحك',
  AppStrings.token: 'token',
  AppStrings.wrongOrder: 'طلب خاطئ',
  AppStrings.serverError: 'خطأ في الخادم',
  AppStrings.error: 'خطأ',
  AppStrings.notExist: 'لا يوجد',
  AppStrings.noInternetConnection: 'لا يوجد اتصال بالانترنت',
  AppStrings.timeOutPleaseTryAgain: 'انتهي الوقت، يرجى المحاولة مرة اخرى',
  AppStrings.confirmLogout: 'تأكيد تسجيل الخروج',
  AppStrings.pleaseEnterOTP: 'الرجاء ادخال رمز التحقق',
  AppStrings.pleaseEnterRightOTP: 'الرجاء ادخال رمز تحقق صحيح',
  AppStrings.pleaseVerifyOTP: 'الرجاء التاكد من رمز التحقيق',
  AppStrings.oTPMayBeWrongTryAgain: 'رمز التحقق قد يكون خاطئ ارجوك حاولا ثانياً',
  AppStrings.successfulLogin: 'تم تسجيل الدخول بنجاح',
  AppStrings.riyad: 'الرياض',
  AppStrings.jeddah: 'جده',
  AppStrings.damam: 'الدمام',
  AppStrings.madinah: 'المدينة',
  AppStrings.makka: 'مكة',
  AppStrings.jezan: 'جيزان',
  AppStrings.abha: 'أبها',
  AppStrings.khobar: 'الخبر',
  AppStrings.taif: 'الطائف',
  AppStrings.tabouk: 'تبوك',
  AppStrings.pleaseSelectCity: 'الرجاء اختيار مدينة',
  AppStrings.pleaseSelectGender: 'الرجاء اختيار الجنس',
};
