import 'package:bacura_app/core/utils/app_strings.dart';

Map<String, String> coreEn = {
  AppStrings.noRouteFounded: 'No Route Founded',
  AppStrings.ar: 'ar',
  AppStrings.en: 'en',
  AppStrings.ar_en: 'EN',
  AppStrings.arabic: 'العربية',
  AppStrings.continueAsVisitor: 'As a Visitor',
  AppStrings.login: 'Login',
  AppStrings.logout: 'Logout',
  AppStrings.edit: 'Edit',
  AppStrings.register: 'Register',
  AppStrings.dontHaveAccount: 'Don’t have an Account?',
  AppStrings.createAccount: 'Create an Account',
  AppStrings.fullName: 'Full Name',
  AppStrings.email: 'Email',
  AppStrings.enterEmail: 'Enter your Email',
  AppStrings.pleaseEnterEmail: 'Please Enter your Email',
  AppStrings.pleaseEnterValidEmail: 'Please Enter Valid Email',
  AppStrings.gender: 'Gender',
  AppStrings.city: 'City',
  AppStrings.mobileNumber: 'Mobile Number',
  AppStrings.enterYourName: 'Enter Your Name',
  AppStrings.pleaseEnterYourName: 'Please Enter Your Name',
  AppStrings.enterYourMobileNumber: 'Enter Your Mobile Number',
  AppStrings.pleaseEnterYourMobileNumber: 'Please Enter Your Mobile Number',
  AppStrings.pleaseEnterValidMobileNumber: 'Please enter a valid phone number',
  AppStrings.pleaseEnterNameAndMobileNumber: 'Please Enter Name & Mobile Number',
  AppStrings.inValidMobileNumber: 'Invalid Mobile Number',
  AppStrings.home: 'Home',
  AppStrings.offers: 'Offers',
  AppStrings.orders: 'orders',
  AppStrings.more: 'More',
  AppStrings.otp: 'OTP Number',
  AppStrings.pleaseEnterOtp: 'Please enter the OTP.',
  AppStrings.otpShouldBeFourDigits: 'OTP must be 4 digits.',
  AppStrings.otpVerified: 'OTP Verified!',
  AppStrings.OtpSentTo: 'OTP Number has already Sent to"',
  AppStrings.changeMobileNumber: 'Change Number',
  AppStrings.verify: 'Verify',
  AppStrings.resend: 'Send OTP Again',
  AppStrings.servicesReadyForYou: 'Our Services are Ready for you!',
  AppStrings.specialServices: 'Special Services made for You',
  AppStrings.language: 'Language',
  AppStrings.aboutBacuraApp: 'About Bacura Tech App',
  AppStrings.technicalSupport: 'Technical Support',
  AppStrings.termsAndConditions: 'Terms and Conditions',
  AppStrings.privacyPolicy: 'Privacy Policy',
  AppStrings.registerAsServiceProvider: 'Register as a Service Provider',
  AppStrings.suggestions: 'Suggestions',
  AppStrings.pleaseEnterSuggestions: 'Please enter your Suggestions',
  AppStrings.pleaseEnterAllData: 'Please Enter All Data',
  AppStrings.rateApp: 'Rate App',
  AppStrings.shareApp: 'Share App',
  AppStrings.bacuraStore: 'Bacura Store',
  AppStrings.customerService: 'Customer Service',
  AppStrings.ok: 'Ok',
  AppStrings.acceptTerms: 'Accept the Privacy Policy and Terms and Conditions',
  AppStrings.continuePayment: 'Continue to pay',
  AppStrings.pay: 'Pay',
  AppStrings.serviceDetails: 'Service Details',
  AppStrings.serviceType: 'Service Type',
  AppStrings.availableServices: 'Available Services',
  AppStrings.next: 'Next',
  AppStrings.setDate: 'Set a suitable Day to  communicate',
  AppStrings.setTime: 'Set a suitable Time to  communicate',
  AppStrings.setLocation: 'Click Icon to Set Location',
  AppStrings.pleaseSelectLocation: 'Please Set The location',
  AppStrings.setCurrentLocation: 'Set Current Location',
  AppStrings.neededServiceDescription: 'Description of the service you need',
  AppStrings.serviceDescription: 'Service Description: ',
  AppStrings.enterServiceDescription: 'Enter Service Description....',
  AppStrings.sendRequest: 'Send Request',
  AppStrings.yourSuggestions: 'Your Suggestions',
  AppStrings.yourSuggestionsHint: 'Your Suggestions is important....',
  AppStrings.send: 'Send',
  AppStrings.notifications: 'Notifications',
  AppStrings.offerDetails: 'Offer Details',
  AppStrings.read_more: 'Read more',
  AppStrings.read_less: 'Read less',
  AppStrings.cancelOrder: 'Cancel Request',
  AppStrings.closeOrder: 'Close the order',
  AppStrings.orderDetails: 'Order Details',
  AppStrings.total: 'Total: ',
  AppStrings.location: 'Location: ',
  AppStrings.paymentMethod: 'Payment Method: ',
  AppStrings.paymentStatus: 'Payment status: ',
  AppStrings.warrantyStatus: 'Warranty status: ',
  AppStrings.manageOrder: 'Request Management',
  AppStrings.orderCancelled: 'Request Cancelled',
  AppStrings.printInvoice: 'Print Invoice',
  AppStrings.customerSupportChat: 'Service Customer Chat',
  AppStrings.consultationScreen: 'Consultation Screen',
  AppStrings.consultationDescription: 'Consultation Description',
  AppStrings.describeYourConsultation: 'describe your Consultation....',
  AppStrings.pleaseDescribeYourConsultation: 'Please describe Your Consultation',
  AppStrings.consultationType: 'Consultation Type',
  AppStrings.cancel: 'Cancel',
  AppStrings.FAQ: 'Frequently asked questions',
  AppStrings.complaints: 'Complaints',
  AppStrings.userGuide: 'User Guide',
  AppStrings.serviceProvider: 'Service Provider',
  AppStrings.technician: 'Technician',
  AppStrings.complaintType: 'Complaint Type',
  AppStrings.complaint: 'Your Complaint',
  AppStrings.enterYourComplaint: 'Enter Your Complaint....',
  AppStrings.pleaseEnterYourComplaint: 'Please enter your Complaint',
  AppStrings.sendComplaint: 'Send Complaint',
  AppStrings.invoice: 'Invoice',
  AppStrings.downloadInvoice: 'Download Invoice',
  AppStrings.save: 'Save',
  AppStrings.termsIntro:
      "Welcome to Bacura Tech Application.\nThese Terms and Conditions provide the legal basis for your use of the Application and its associated services.\n\nAcceptance of Terms: By using the Application, you agree to be bound by these Terms. If you do not agree to any of these terms, please do not use the application",
  AppStrings.termsDefinitions: '1. Definitions:',
  AppStrings.termsDefinitionsContent:
      "- Application: refers to the Bacura Application and all its associated services and content.\n- Services: means all services and features provided by the application.\n- User: Any person who uses the application or any of its services.\n- Service Provider: Any party that provides actual services to end users or customers\n- Service Provider: Any party that provides the infrastructure, technologies, or systems on which the application depends",
  AppStrings.termsConditions: '2. Terms of use:',
  AppStrings.termsConditionsContent:
      "- Eligibility: Users must be of legal age to enter into a binding contract or have the consent of their parent or legal guardian to use the App.\n\n- Acceptable Use: Users must use the App only for the purposes for which the App was designed and in a manner that does not infringe the rights of others or adversely affect the operation of the App. This includes not using the App for fraud, harassment, or any illegal use.\n\n- Account Creation: You must create an account in order to use the App Services.\n\n- Attaching Documents: Use of some App Services may require the attachment of documents. Users must provide true, accurate, and current information when submitting such documents, and ensure that all data and information provided complies with the specific requirements of the Service.\n\n- Continued Use: Once we post amendments to the Terms, your use of the App after such update shall be deemed acceptance of the amended Terms.\n\n- Termination of Use: We reserve the right to terminate or suspend your access to the App at any time, without prior notice, if you violate these Terms.",
  AppStrings.termsCopyRights: '3. Intellectual Property Rights:',
  AppStrings.termsCopyRightsContent:
      "All copyrights, trademarks and other rights in the App and its contents are owned by us. No part of the App may be copied, distributed or modified without our express permission.",
  AppStrings.termsLimitationOfLiability: "4. Limitation of Liability:",
  AppStrings.termsLimitationOfLiabilityContent:
      "The Company disclaims any responsibility and does not warrant that the Application will be free from errors or defects or that the Services will be available at all times.",
  AppStrings.termsChanges: "5. Changes",
  AppStrings.termsChangesContent:
      "- Modification of Terms: The Company has the right to modify these Terms at any time.\n\n- Cancellation of Service: The Company has the right to cancel the Service or any part there of at any time.",
  AppStrings.contactUs: "6. Contact us:",
  AppStrings.contactUsContent:
      "If you have any questions about this policy, please contact us at (Bacura@gmail.com) or (050428282).",
  AppStrings.privacyPolicyIntro:
      "Welcome to Bacura Tech Application.\n\nWe at Bacura Technologies are committed to protecting your privacy and ensuring the security of your personal information. This privacy policy explains how we collect, use and protect the information you provide to us when you use the application.",
  AppStrings.privacyCollectionOfInformation: "1. Collection of information:",
  AppStrings.privacyCollectionOfInformationContent:
      "We collect personal information that you voluntarily provide on the App, such as your name, email address, phone number, and other information we may need to provide the Service and to send you notices, updates, or information related to the Service or about special offers and new features. We collect technical information about how you use the App, and a record of your activity on the App, including the pages you visit, the features you use, and the time you spend on the App, for the purpose of improving your user experience, the quality of the Service, and analyzing App usage. We retain your information only for as long as necessary to fulfill the purposes for which it was collected, or as required by law.",
  AppStrings.privacyInformationProtection: "2. Information Protection:",
  AppStrings.privacyInformationProtectionContent:
      "We are committed to protecting your personal information. We take appropriate security measures to protect your personal information from unauthorized access, use, disclosure, alteration or destruction. This includes using encryption and cybersecurity technologies to maintain an up-to-date security system.",
  AppStrings.privacySharingInformation: "3. Sharing information:",
  AppStrings.privacySharingInformationContent:
      "We may share your personal information with third parties but only to the extent necessary to fulfill the purposes set out in this policy, such as:\n- Service providers and suppliers: companies we contract with to provide certain services on our behalf.\n- Partners: companies we collaborate with to provide joint offerings.\n- Government agencies: if required by law.",
  AppStrings.changesToThePrivacyPolicy: "4. Changes to the Privacy Policy:",
  AppStrings.changesToThePrivacyPolicyContent:
      "We reserve the right to modify this policy at any time. We will notify you of any material changes through the App or by email.",
  AppStrings.privacyUserRights: "5. User Rights:",
  AppStrings.privacyUserRightsContent:
      "You can access and correct your personal information through your account settings in the app or by contacting us directly. You can unsubscribe from marketing messages or delete your account at any time through your account settings or by contacting customer service.",
  AppStrings.aboutUs:
      "With Bacura Tec App, We provide you with an integrated solution to manage your Technical, Smart and Security needs with ease and professionalism. Whether you are looking to install High-Quality Surveillance Cameras, Smart Systems, or Innovative Technical Solutions for your Home or Workplace, our Application is the Perfect Choice.",
  AppStrings.aboutUsContent:
      "We guarantee you High-Quality Technical Services with Efficiency and speed of implementation, with a professional Team around the clock and continuous Technical Support, your Security and Comfort are now at your Fingertips.",
  AppStrings.ourLocation: "Our Website:   ",
  AppStrings.uploadImage: "Image uploaded",
  AppStrings.takePicture: "Take a Picture",
  AppStrings.selectFromGallery: "Choose from Gallery",
  AppStrings.offerRequest: "Request The Offer",
  AppStrings.browseAppWithoutRegister: 'You can browse the application without registering.',
  AppStrings.appLanguage: 'App Language',
  AppStrings.male: 'Male',
  AppStrings.female: 'Female',
  AppStrings.typeMessageHere: 'Write your message here',
  AppStrings.welcomeToBacuraApp: 'Welcome To Bacura App',
  AppStrings.confirm: 'Confirm',
  AppStrings.yourComplaintSentSuccessfully: 'Your complaint has been sent successfully.',
  AppStrings.yourSuggestionSentSuccessfully: 'Your suggestion has been sent successfully.',
  AppStrings.yourSuggestionSentSuccessfullyMsg:
      'We care about your interest and thank you for your suggestion. Your suggestion will be reviewed and we will congratulate you on your success.',
  AppStrings.token: 'token',
  AppStrings.wrongOrder: 'Wrong order',
  AppStrings.serverError: 'Server error',
  AppStrings.error: 'Wrong',
  AppStrings.notExist: 'Nothing',
  AppStrings.noInternetConnection: 'No internet connection',
  AppStrings.timeOutPleaseTryAgain: 'Time is up, please try again.',
  AppStrings.confirmLogout: 'Confirm logout',
  AppStrings.pleaseEnterOTP: 'Please Enter The OTP',
  AppStrings.pleaseEnterRightOTP: 'Please enter a valid OTP',
  AppStrings.pleaseVerifyOTP: 'Please check the OTP',
  AppStrings.oTPMayBeWrongTryAgain: 'The OTP may be wrong. Please try again.',
  AppStrings.successfulLogin: 'You have been logged in successfully',
  AppStrings.riyad: 'Riyadh',
  AppStrings.jeddah: 'Jeddah',
  AppStrings.damam: 'Dammam',
  AppStrings.madinah: 'Madinah',
  AppStrings.makka: 'Mecca',
  AppStrings.jezan: 'Jizan',
  AppStrings.abha: 'Abha',
  AppStrings.khobar: 'Khobar',
  AppStrings.taif: 'Taif',
  AppStrings.tabouk: 'Tabuk',
  AppStrings.pleaseSelectCity: 'Please select a city',
  AppStrings.pleaseSelectGender: 'Please select gender',
};
